name: Deploy Next.js Portfolio

on:
  push:
    branches: [main] # deploy whenever main branch is updated

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build && npm run export

      - name: Deploy to ravin1100.github.io
        run: |
          cd out
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy new portfolio"
          git push --force https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/ravin1100/ravin1100.github.io.git main
